language: csharp
solution: GL_BreakIt.sln
before_install:
    - chmod a+x ./travis_scripts/run-tests.sh
install:
    - travis_retry nuget restore -source "https://www.nuget.org/api/v2" ./GL_BreakIt.sln
script:
    - travis_scripts/run-tests.sh